#+TITLE: Emacs Settings

* Emacs packages repo
** repo
#+BEGIN_SRC emacs-lisp
(require 'package)
(let* ((no-ssl (and (memq system-type '(windows-nt ms-dos))
                    (not (gnutls-available-p))))
       (proto (if no-ssl "http" "https")))
  ;; Comment/uncomment these two lines to enable/disable MELPA and MELPA Stable as desired
  (add-to-list 'package-archives (cons "melpa" (concat proto "://melpa.org/packages/")) t)
  ;;(add-to-list 'package-archives (cons "melpa-stable" (concat proto "://stable.melpa.org/packages/")) t)
  (when (< emacs-major-version 24)
    ;; For important compatibility libraries like cl-lib
    (add-to-list 'package-archives '("gnu" . (concat proto "://elpa.gnu.org/packages/")))))
(package-initialize)
#+END_SRC
** use-package
This package downloads and install packages from melpa and elpa
#+BEGIN_SRC emacs-lisp
(require 'use-package)
#+END_SRC
* UI settings
** Turn off menu bar
#+BEGIN_SRC emacs-lisp
(menu-bar-mode -1)
#+END_SRC
** Turn off splas screen
#+BEGIN_SRC emacs-lisp
(setq inhibit-splash-screen t)
#+END_SRC
** Change frame name for of emacs
Borrowed from: http://mescal.imag.fr/membres/arnaud.legrand/misc/init.php
#+BEGIN_SRC emacs-lisp
  (setq frame-title-format
    '("Emacs - " (buffer-file-name "%f"
      (dired-directory dired-directory "%b"))))
#+END_SRC
** set font
#+BEGIN_SRC emacs-lisp
  (set-frame-font "Fira Mono-10")
#+END_SRC
** theme
#+BEGIN_SRC emacs-lisp
  (use-package doneburn-theme
    :ensure t
    :config (load-theme 'doneburn 'no-confirm))
#+END_SRC
** line and column numbering
#+BEGIN_SRC emacs-lisp
  (line-number-mode 1)
  (column-number-mode 1)
#+END_SRC
** utf-8 as default
#+BEGIN_SRC emacs-lisp
  (set-terminal-coding-system 'utf-8)
  (set-keyboard-coding-system 'utf-8)
  (prefer-coding-system 'utf-8)
#+END_SRC
** which-key
which-key adds popup with avinable keybindings
#+BEGIN_SRC emacs-lisp
  (use-package which-key
    :ensure t
    :config (which-key-mode))
#+END_SRC
** ivy, swiper and counsel
#+BEGIN_SRC emacs-lisp
  (use-package ivy
    :ensure t
    :config (ivy-mode 1))
  (use-package counsel
    :ensure t)
  (use-package swiper
    :ensure t)

  (setq ivy-use-virtual-buffers t)
  (setq ivy-count-format "(%d/%d) ")
  (global-set-key (kbd "C-s") 'swiper)
  (global-set-key (kbd "M-x") 'counsel-M-x)
  (global-set-key (kbd "C-x C-f") 'counsel-find-file)
  (global-set-key (kbd "<f1> f") 'counsel-describe-function)
  (global-set-key (kbd "<f1> v") 'counsel-describe-variable)
  (global-set-key (kbd "<f1> l") 'counsel-find-library)
  (global-set-key (kbd "<f2> i") 'counsel-info-lookup-symbol)
  (global-set-key (kbd "<f2> u") 'counsel-unicode-char)
#+END_SRC
Fuzzy finder regexp for ivy
#+BEGIN_SRC emacs-lisp
  (setq ivy-re-builders-alist
        '((t . ivy--regex-fuzzy)))
#+END_SRC
** TODO setup does three
* Autocompletion
For autocompletion I use company-mode
#+BEGIN_SRC emacs-lisp
  (use-package company
    :ensure t)
  (add-hook 'after-init-hook 'global-company-mode)
#+END_SRC
* Tools
** Git
For git I use magit.
#+BEGIN_SRC emacs-lisp
  (use-package magit
    :ensure t)
#+END_SRC
Some keybindings
#+BEGIN_SRC emacs-lisp
  (global-set-key (kbd "C-x g") 'magit-status)
  (global-set-key (kbd "C-x M-g") 'magit-dispatch-popup)
#+END_SRC
** Linter
   For linting I use flycheck
#+BEGIN_SRC emacs-lisp
  (use-package flycheck
    :ensure t)
  (global-flycheck-mode)
#+END_SRC
* Lang
** PHP
   First we need to install php-mode, which adds support for PHP files.
#+BEGIN_SRC emacs-lisp
  (use-package php-mode
    :ensure t)
#+END_SRC
   Because I work mostly with WordPress I have setup php-mode with WP coding style.
#+BEGIN_SRC emacs-lisp
  (add-hook 'php-mode-hook 'php-enable-wordpress-coding-style)
#+END_SRC
   Add and use web-mode for mixed html and php code (templates)
#+BEGIN_SRC emacs-lisp
  (use-package web-mode
    :ensure t)

  (add-to-list 'auto-mode-alist '("\\.phtml\\'" . web-mode))
  (add-to-list 'auto-mode-alist '("\\.tpl\\.php\\'" . web-mode))
  (add-to-list 'auto-mode-alist '("\\.html\\.twig\\'" . web-mode))
  (add-to-list 'auto-mode-alist '("\\.html?\\'" . web-mode))
           
#+END_SRC
* Org mode
Let's start by setting default org-mode directory.
#+BEGIN_SRC emacs-lisp
  (setq org-directory "~/org/")
#+END_SRC
Some basic settings
#+BEGIN_SRC emacs-lisp
  (setq org-hide-leading-stars t)
  (setq org-alphabetical-lists t)
  (setq org-src-fontify-natively t)  ;; you want this to activate coloring in blocks
  (setq org-src-tab-acts-natively t) ;; you want this to have completion in blocks
  (setq org-hide-emphasis-markers t) ;; to hide the *,=, or / markers
  (setq org-pretty-entities t)       ;; to have \alpha, \to and others display as utf8 http://orgmode.org/manual/Special-symbols.html
#+END_SRC
* Evil mode
